apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventorytracking-02-db-pvc
  namespace: inventory02-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
