apiVersion: v1
kind: ConfigMap
metadata:
  name: timesheettracking-content
  namespace: timesheet-ns
data:
  web: |
    TimesheetTracking web service is running
  status: |
    TimesheetTracking service is healthy
  default.conf: |
    server {
        listen 80;
        default_type text/plain;

        location / {
            root /usr/share/nginx/html;
        }
    }
